# Generated by Django 4.1.7 on 2023-04-28 13:33

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('dirittodecent', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bannedusers',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('target'), models.OrderBy(django.db.models.functions.text.Lower('sender'), descending=True), name='unique_ban'),
        ),
    ]
