# Generated by Django 4.1.7 on 2023-05-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirittodecent', '0002_bannedusers_unique_ban'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licenza',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('proprietario', models.CharField(max_length=100)),
                ('tipo', models.BooleanField()),
                ('autore', models.CharField(max_length=100)),
                ('titolo', models.CharField(max_length=100)),
                ('data', models.PositiveIntegerField(default=0)),
                ('time', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='testo',
            name='data',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testo',
            name='sender',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testo',
            name='titolo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
