# Generated by Django 4.2.1 on 2023-05-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirittodecent', '0003_licenza_testo_data_testo_sender_testo_titolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenza',
            name='id_testo',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
