# Generated by Django 4.1.7 on 2023-04-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirittodecent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testo',
            name='trust',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
